spring:
  cloud:
    consul:
      discovery:
        instance-id: "${spring.application.name}:${random.int[1,999999]}"
      config:
        enabled: false
  application:
    name: account-service

server:
  port: 0
